export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_WO_LIST = 'GET_WO_LIST';
export const ADD_WO_TO_LIST = 'ADD_WO_TO_LIST';
export const UPDATE_WO_LIST = 'UPDATE_WO_LIST';
export const GET_WO = 'GET_WO';
export const SAVE_WO = 'SAVE_WO';
export const CREATE_WO = 'CREATE_WO';
export const SAVE_MAIN = 'SAVE_MAIN';
export const SAVE_ITEMS = 'SAVE_ITEMS';
export const CLEAR_WO = 'CLEAR_WO';

export const GET_PROFILE = 'GET_PROFILE';
export const SAVE_PROFILE = 'SAVE_PROFILE';

export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const SET_CURRENT_REMARK = 'SET_CURRENT_REMARK';
export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';
export const SET_CURRENT_MATERIAL_TAB = 'SET_CURRENT_MATERIAL_TAB';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';

//MATERIAL
export const GET_MATERIAL = 'GET_MATERIAL';      
export const SAVE_MATERIAL = 'SAVE_MATERIAL';
export const SAVE_BOARDS = 'SAVE_BOARDS';
export const SAVE_LAMINATES = 'SAVE_LAMINATES';
export const SAVE_MATERIALCODES = 'SAVE_MATERIALCODES';
export const SAVE_PROFILES = 'SAVE_PROFILES';
export const SAVE_EDGEBANDS = 'SAVE_EDGEBANDS';
export const CLEAR_MATERIAL = 'CLEAR_MATERIAL';    

//REMARKS
export const SAVE_REM_PROFILES = 'SAVE_REM_PROFILES';      

//CUSTOMER
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';   
export const GET_CUSTOMER = 'GET_CUSTOMER';      
export const SAVE_CUSTOMER = 'SAVE_CUSTOMER';
export const ADD_CUSTOMER_TO_LIST = 'ADD_CUSTOMER_TO_LIST';
export const UPDATE_CUSTOMER_LIST = 'UPDATE_CUSTOMER_LIST';
